apiVersion: v1
kind: Service
metadata:
  name: sftpgo-web
  namespace: sftpgo
spec:
  type: LoadBalancer
  selector:
    app: sftpgo
  ports:
    - protocol: TCP
      port: 8097
      targetPort: 8097
      name: web
---
apiVersion: v1
kind: Service
metadata:
  name: sftpgo-ftp
  namespace: sftpgo
spec:
  type: LoadBalancer
  selector:
    app: sftpgo
  ports:
    - protocol: TCP
      port: 21
      targetPort: 21
      name: ftp
    - protocol: TCP
      port: 2121
      targetPort: 2121
      name: ftp-passive-1
    - protocol: TCP
      port: 2122
      targetPort: 2122
      name: ftp-passive-2
    - protocol: TCP
      port: 2123
      targetPort: 2123
      name: ftp-passive-3
    - protocol: TCP
      port: 2124
      targetPort: 2124
      name: ftp-passive-4
    - protocol: TCP
      port: 2125
      targetPort: 2125
      name: ftp-passive-5
    - protocol: TCP
      port: 2126
      targetPort: 2126
      name: ftp-passive-6
    - protocol: TCP
      port: 2127
      targetPort: 2127
      name: ftp-passive-7
    - protocol: TCP
      port: 2128
      targetPort: 2128
      name: ftp-passive-8
    - protocol: TCP
      port: 2129
      targetPort: 2129
      name: ftp-passive-9
    - protocol: TCP
      port: 2130
      targetPort: 2130
      name: ftp-passive-10
---
apiVersion: v1
kind: Service
metadata:
  name: sftpgo-sftp
  namespace: sftpgo
spec:
  type: LoadBalancer
  selector:
    app: sftpgo
  ports:
    - protocol: TCP
      port: 2022
      targetPort: 2022
      name: sftp